# Setup
title:               Jeff Victorino
tagline:             'Dev Portfolio'
description:         'Porfolio made by Jeff Victorino, based off poole/Lanyon'
url:                 https://jeffafav.github.io/Jekyll-Portfolio/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-github-metadata

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
